Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.default = {
    WX_HEADER_Token: "X-WX-Token",
    ERR_WX_LOGIN_FAILED: "ERR_WX_LOGIN_FAILED",
    ERR_WX_GET_USER_INFO: "ERR_WX_GET_USER_INFO",
    ERR_LOGIN_SESSION_NOT_RECEIVED: "ERR_LOGIN_MISSING_SESSION",
    ERR_CHECK_LOGIN_FAILED: "ERR_CHECK_LOGIN_FAILED",
    WX_DOMAIN_URL_FAILED: "WX_DOMAIN_URL_FAILED",
    WX_SESSION_WXAPP_SESSION: "WX_SESSION_WXAPP_SESSION"
};